# Reference: https://docs.antora.org/antora/latest/playbook/

site:
  title: Clean Documentation Template
  url: https://qaware.github.io/clean-documentation-template

content:
  sources:
    - url: .
      start_path: docs

ui:
  bundle:
    # You should supply your own bundle with custom company colors etc.
    # https://gitlab.com/antora/antora-ui-default
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  # You can adapt the bundle on the fly while running antora
  # https://docs.antora.org/antora/latest/playbook/ui-supplemental-files/
  # The header-content.hbs has some nonsense menu which is removed in the override file
  supplemental_files: ./supplemental-ui

antora:
  extensions:
    # Add offline search
    # https://gitlab.com/antora/antora-lunr-extension
    - require: '@antora/lunr-extension'

asciidoc:
  extensions:
    # Add kroki as general purpose code-to-diagram converter
    # https://kroki.io
    # https://github.com/asciidoctor/asciidoctor-kroki
    - asciidoctor-kroki
  attributes:
    kroki-fetch-diagram: true # Download images from kroki and do not fetch at "read time"
    # If you don't want to send your data to kroki.io you can run your own kroki container/server
    # https://github.com/asciidoctor/asciidoctor-kroki#using-your-own-kroki
    # kroki-server-url: http://localhost:8000 # For locally running kroki
