# Reference: https://github.com/errata-ai/vale-action

name: Verify
on:
  push:
    branches: [main]
  pull_request: ~

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.0
        with:
          fail_on_error: true
